// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qglghefexghfymlrtvqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbGdoZWZleGdoZnltbHJ0dnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjQ0NTAsImV4cCI6MjA2NzQ0MDQ1MH0.8oJr2ECjEd4Slbm7q5fF_PDNFvI0rEdO-yj5xmgEqUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});